### ISSUE TITLE
Publishing the examples or not

### ISSUE THREAD

**Issue by aliok** [aerogear/apollo-voyager-server#35]
I setup the publishing process for this project.

Last step is `npm run publish` which tells lerna to publish each package.

All packages are published nicely, but `examples` is also a module handled by lerna and it is marked as private and can't be published.

See https://circleci.com/gh/aerogear/apollo-voyager-server/142

Easiest solution is to publish that package as well.

Alternative is somehow configure lerna to not publish this package. I haven't looked into this right now.

If you check https://circleci.com/gh/aerogear/apollo-voyager-server/142, you will see it as red, but in fact all necessary packages are published nicely.

Don't want to work on this right now and just creating an issue here.

**Comment by aliok** [comment]
cc @darahayes @wtrocki

**Comment by wtrocki** [comment]
`lerna publish --ignore package`


https://github.com/lerna/lerna/blob/master/core/filter-options/README.md

**Comment by darahayes** [comment]
Let's try `--no-private` for now.
