### ISSUE TITLE
[CommunityFeedback] Advanced conflict resolution in Voyager

### ISSUE THREAD

**Issue by wtrocki** [aerogear/apollo-voyager-server#46]
## Motivation

Provide conflict resolution mechanism that provides all the data required to resolve conflict. 
Conflicts should be resolved to enable merging objects together without losing any changes in the process. I In case when changes are made inside the same field appropriate strategy should define how overwrite should happen.

## Approaches

Conflicts should be resolved on client and server depending on the developer choice.

### Provide diff mechanism on the server by persisting previous state

Persist previous state of the data so server side version can be compared against it giving diff.
When conflict will happen server or client will have access to base object that will allow users to perform 3 way merge using any strategy that is possible. This way we can also provide diffs for client that can also provide strategies or even resolve the client visually (same as when doing git merge)

Alternatively to storing entire objects we can persist diffs, however this will make comparison process more complex

![basechanges](https://user-images.githubusercontent.com/981838/50833261-874c2c00-1348-11e9-8cbc-9c34f7ab3fec.png)

When resolving conflicts changes are compared against base giving nice diff for server and client.
This aproach is already implemented, however we require users handle persistence for previous states, 
which is additional overhead.

#### Pros

- Enables tracking changes and auditing them
- Enables full flexibility in terms of conflict resolution

#### Cons

- Requires separate storage (however we can provide helpers to handle those later)

### Force client to operate on diff data

Clients can send only updates that were actually happening.
For example for mutation:
`updateTask(id:ID!,name: String, description: String): Task`

Developer can send only name field and ignore description that was not changed.
This will give us ability to know what was changed as only changed fields are sent to mutations
Clients could send to server only the data that was actually changed. This will imply that mutations should not have required fields as this will prevent this mechanism from happening.
This also means that clients will need to perform diffing logic to determine changesets,
which can be tricky.

With this aproach changes that are happening on the server are ignored. Only client diff is applied 
on top of the server making it impossible to employ more complex strategies and use cases.

![screen shot 2019-01-08 at 1 50 16 pm](https://user-images.githubusercontent.com/981838/50834613-6980c600-134c-11e9-8f54-7b2f5d8b85f9.png)

##### Pros

- Works almost out of the box on server
- Handling logic is very simple to understand and implement for developers

#### Cons

- Requires developers to change the way they work with GraphQL -  to do the diff 
- Limits how schema can be build
- Ability to only apply the client side changeset (no server/base comparision)

**Comment by wtrocki** [comment]
ping @aerogear/voyager Going to build approaches for conflict resolution here.

**Comment by wtrocki** [comment]
Taking one option do not mean we cannot provide another - option 1 requires persistence to be defined and it's optional at the moment. Option 2 can work out of the box for the cases where users will actually configure their framework to send diffs. There is not much technical overhead for doing and documenting both options from the moment as both provide some unique capabilities and it will give users better choice for their needs.

**Comment by wtrocki** [comment]
Implementation in #45 is to provide diff capabilities for GraphQL implementations. 
Old sync worked only with diff and had freedom over how data was send and processed. GraphQL do not have this ability because users define strict rules what needs to be returned from server. 
I have been reading very deeply over the last weeks trying to get us into something:

- That will provide ability to see what was changed (it is high demand feature in graphql communities upstream)
- Have set of clear steps that developers needs to follow to enable it.
- Abstract from elements that are provided by developers (data sources etc.)

Consulted over with graphql community when building it, hoping to get some comments on this as well.

**Comment by wei-lee** [comment]
@wtrocki cool. do you have an issue somewhere for the discussion upstream?

**Comment by wtrocki** [comment]
I put more thoughts into this and I think we can bake two approaches into single one.
